import 'package:flutter/material.dart';
import 'package:my_school_friend/localization/app_localization.dart';
import 'package:my_school_friend/widgets/chemichalContainers.dart';

class LantanidlerAktinidler extends StatelessWidget {
  const LantanidlerAktinidler({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: RichText(
          text: TextSpan(
            text: "${AppLocalizations.of(context).translate('lan')} ",
            style: TextStyle(
                color: Colors.white, fontSize: 23, fontWeight: FontWeight.w600),
            children: [
              TextSpan(
                text: "${AppLocalizations.of(context).translate("and")} ",
              ),
              TextSpan(
                text: AppLocalizations.of(context).translate('act'),
              )
            ],
          ),
        ),
        flexibleSpace: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.centerLeft,
              end: Alignment.centerRight,
              colors: <Color>[
                Colors.purple[100],
                Colors.pink[200],
              ],
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Center(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              Row(
                children: [
                  buildLanthanides(context),
                  SizedBox(width: 50),
                  buildActinides(context),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Column buildActinides(BuildContext context) {
    return Column(
      children: [
        Text(
          AppLocalizations.of(context).translate('act'),
          style: TextStyle(
            color: Colors.black87,
            fontSize: 25,
          ),
        ),
        SizedBox(
          height: 10,
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "89",
          t2: "Ac",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "90",
          t2: "Th",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "91",
          t2: "Pa",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "92",
          t2: "U",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "93",
          t2: "Np",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "94",
          t2: "Pu",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "95",
          t2: "Am",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "96",
          t2: "Cm",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "97",
          t2: "Bk",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "98",
          t2: "Cf",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "99",
          t2: "Es",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "100",
          t2: "Fm",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "101",
          t2: "Md",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "102",
          t2: "No",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "103",
          t2: "Lr",
          tGrup: "",
          tPeriot: "",
          color: Colors.pink[200],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
      ],
    );
  }

  Column buildLanthanides(BuildContext context) {
    return Column(
      children: [
        Text(
          AppLocalizations.of(context).translate('lan'),
          style: TextStyle(
            color: Colors.black87,
            fontSize: 25,
          ),
        ),
        SizedBox(
          height: 10,
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "57",
          t2: "La",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "58",
          t2: "Ce",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "59",
          t2: "Pr",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "60",
          t2: "Nd",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "61",
          t2: "Pm",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "62",
          t2: "Sm",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "63",
          t2: "Eu",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "64",
          t2: "Gd",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "65",
          t2: "Tb",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "66",
          t2: "Dy",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "67",
          t2: "Ho",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "68",
          t2: "Er",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "69",
          t2: "Tm",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "70",
          t2: "Yb",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
        ChemichalContainer(
          onPress: () {},
          t1: "71",
          t2: "Lu",
          tGrup: "",
          tPeriot: "",
          color: Colors.purple[100],
          textColor: Colors.black,
          grupAndPeriotColor: Colors.white,
          borderr: Border.all(),
        ),
      ],
    );
  }
}
